services:
  esb_echo:
    image: xnet/esb:0.1.0
    ports:
      - "8085:8080"
    env_file:
      - path: .env-echo
        required: false
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dpolyglot.engine.WarnInterpreterOnly=false
    volumes:
      - "./flows/flows.yaml:/flows/flows.yaml"
  #
  ## ESB Logistica
  #
  esb_logistica:
    image: xnet/esb:0.1.0
    ports:
      - "8086:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dpolyglot.engine.WarnInterpreterOnly=false

  #
  ## Componente de monitoreo
  #
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Puerto predeterminado de Prometheus UI
    volumes:
      # Monta el archivo de configuración LOCAL en la ruta esperada por Prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      # Monta un volumen para persistir los datos
      - prometheus_data:/prometheus 
    command: 
      # Sobreescribe el CMD para asegurar que se use la configuración
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

volumes:
  prometheus_data:

